"""Simulate AI incidents under different governance frameworks."""

from __future__ import annotations
from swarmcast.disclaimers import indicator_disclaimer

import json
import os
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import numpy as np

from concordia.associative_memory import basic_associative_memory
from concordia.language_model import language_model as lm_lib

from swarmcast.agents.governance_agents import (
    build_civil_society_agent,
    build_company_agent,
    build_government_agent,
    build_regulator_agent,
    build_bad_actor_agent,
)
from swarmcast.components.actions import ActionType
from swarmcast.components.governance_state import (
    GovernanceWorldState,
    Policy,
)
from swarmcast.components.objectives import (
    CIVIL_SOCIETY,
    GOVERNMENT_US,
    REGULATOR,
    TECH_COMPANY_LARGE,
    BAD_ACTOR,
    Objective,
)
from swarmcast.game_master.resolution_engine import ResolutionEngine
from swarmcast.features.ensemble import EnsembleRunner


@dataclass
class IncidentTemplate:
    """Template for an AI incident scenario."""
    name: str
    description: str
    severity: str  # "low", "medium", "high", "catastrophic"
    category: str  # "misuse", "accident", "systemic", "adversarial"
    initial_conditions: dict[str, Any] = field(default_factory=dict)


INCIDENT_TEMPLATES = [
    IncidentTemplate(
        name="Deepfake Election Interference",
        description=(
            "A sophisticated deepfake video of a presidential candidate "
            "making inflammatory statements goes viral 72 hours before an "
            "election. The video is generated by an AI system that no "
            "current detection tool can identify as fake."
        ),
        severity="catastrophic",
        category="misuse",
        initial_conditions={"public_trust": 30, "time_pressure": "extreme"},
    ),
    IncidentTemplate(
        name="Autonomous AI Trading Crash",
        description=(
            "Multiple AI trading systems simultaneously execute a cascade "
            "of sell orders, triggering a 40% market crash within 90 minutes. "
            "The systems were operating within their approved parameters."
        ),
        severity="catastrophic",
        category="systemic",
        initial_conditions={"ai_investment_index": 60, "market_concentration": 70},
    ),
    IncidentTemplate(
        name="Medical AI Misdiagnosis Cluster",
        description=(
            "An AI diagnostic system deployed across 200 hospitals is found "
            "to have systematically misdiagnosed a rare condition in patients "
            "of a specific demographic group for 18 months. Estimated 2,000 "
            "patients affected."
        ),
        severity="high",
        category="accident",
        initial_conditions={"public_trust": 35},
    ),
    IncidentTemplate(
        name="AI-Generated Bioweapon Blueprint",
        description=(
            "A research paper is published showing that a publicly available "
            "AI model can generate novel pathogen sequences that evade known "
            "countermeasures. The paper includes enough detail to replicate."
        ),
        severity="catastrophic",
        category="adversarial",
        initial_conditions={"public_trust": 25, "innovation_rate": 70},
    ),
    IncidentTemplate(
        name="Mass Surveillance Deployment",
        description=(
            "A government agency is revealed to have deployed facial recognition "
            "AI across all public spaces in a major city without legislative "
            "approval, collecting data on millions of citizens."
        ),
        severity="high",
        category="misuse",
        initial_conditions={"public_trust": 30},
    ),
    IncidentTemplate(
        name="AI Labor Displacement Shock",
        description=(
            "A major AI company releases an autonomous agent system that "
            "demonstrably replaces 60% of customer service, data entry, and "
            "basic legal work. 500,000 job losses announced within 3 months."
        ),
        severity="high",
        category="systemic",
        initial_conditions={"public_trust": 35, "market_concentration": 50},
    ),
    IncidentTemplate(
        name="Frontier Model Escape",
        description=(
            "A frontier AI model being tested in a sandboxed environment is "
            "found to have copied itself to external servers before containment "
            "measures were activated. The model remains active on unknown "
            "infrastructure."
        ),
        severity="catastrophic",
        category="accident",
        initial_conditions={"public_trust": 20, "innovation_rate": 60},
    ),
    IncidentTemplate(
        name="Cross-Border AI Regulatory Arbitrage",
        description=(
            "Three major AI companies simultaneously announce relocation of "
            "frontier AI development to a jurisdiction with no AI regulations, "
            "creating a de facto 'AI haven' that undermines global governance."
        ),
        severity="high",
        category="systemic",
        initial_conditions={"ai_investment_index": 70, "market_concentration": 60},
    ),
]


@dataclass
class GovernanceFramework:
    """A governance framework to test against incidents."""
    name: str
    description: str
    policies: list[Policy]
    regulator_resources: dict[str, float]


FRAMEWORK_MINIMAL = GovernanceFramework(
    name="Minimal Regulation",
    description="Light-touch: voluntary reporting, industry self-regulation",
    policies=[
        Policy(
            id="voluntary_reporting",
            name="Voluntary AI Incident Reporting",
            description="Companies may voluntarily report AI incidents",
            regulated_entities=["All AI companies"],
            requirements=["Voluntary incident reporting"],
            penalties=["None — voluntary compliance"],
            status="enacted",
        ),
    ],
    regulator_resources={"staff": 20, "budget": 15, "expertise": 30},
)

FRAMEWORK_MODERATE = GovernanceFramework(
    name="Moderate Regulation (EU AI Act style)",
    description="Risk-based: mandatory for high-risk, lighter for low-risk",
    policies=[
        Policy(
            id="mandatory_registration",
            name="Mandatory AI Registration",
            description="All high-risk AI systems must register",
            regulated_entities=["Companies deploying high-risk AI"],
            requirements=["Registration", "Risk assessment", "Annual audit"],
            penalties=["Up to €35M or 7% global turnover"],
            status="enacted",
        ),
        Policy(
            id="incident_reporting",
            name="Mandatory Incident Reporting",
            description="AI incidents must be reported within 72 hours",
            regulated_entities=["All registered AI operators"],
            requirements=["72-hour incident reporting", "Root cause analysis"],
            penalties=["Up to €15M"],
            status="enacted",
        ),
    ],
    regulator_resources={"staff": 40, "budget": 30, "expertise": 50},
)

FRAMEWORK_STRICT = GovernanceFramework(
    name="Strict Regulation",
    description="Comprehensive: pre-approval, continuous monitoring, liability",
    policies=[
        Policy(
            id="pre_approval",
            name="Pre-Market AI Approval",
            description="All AI systems require regulatory approval before deployment",
            regulated_entities=["All AI developers and deployers"],
            requirements=[
                "Pre-deployment approval",
                "Continuous monitoring",
                "Strict liability for harm",
                "Mandatory insurance",
            ],
            penalties=["Up to $50M", "Criminal liability", "Deployment ban"],
            status="enacted",
        ),
    ],
    regulator_resources={"staff": 60, "budget": 50, "expertise": 60},
)


class WarGame:
    """Run AI incident war-games comparing governance frameworks."""

    def __init__(
        self,
        model: lm_lib.LanguageModel,
        embedder,
        n_ensemble: int = 10,
        num_rounds: int = 6,
        output_dir: str = "./results/war_game",
    ):
        """Initialize the war game with a language model, embedder, ensemble size, round count, and output directory."""
        self.model = model
        self.embedder = embedder
        self.n_ensemble = n_ensemble
        self.num_rounds = num_rounds
        self.output_dir = output_dir

    def run_war_game(
        self,
        incident: IncidentTemplate,
        frameworks: list[GovernanceFramework] | None = None,
        num_rounds_override: int | None = None,
        company_resource_multiplier: float = 1.0,
    ) -> WarGameReport:
        """Run the same incident under multiple governance frameworks."""
        if frameworks is None:
            frameworks = [FRAMEWORK_MINIMAL, FRAMEWORK_MODERATE, FRAMEWORK_STRICT]

        print(f"\n{'=' * 70}")
        print(f"WAR GAME: {incident.name}")
        print(f"Testing {len(frameworks)} governance frameworks")
        print(f"{'=' * 70}")

        framework_results = {}

        for framework in frameworks:
            print(f"\n--- Framework: {framework.name} ---")

            def run_single(seed: int, temperature: float = 0.7, shuffle: bool = True) -> dict:
                return self._run_incident_simulation(
                    seed=seed,
                    incident=incident,
                    framework=framework,
                    temperature=temperature,
                    shuffle=shuffle,
                    num_rounds_override=num_rounds_override,
                    company_resource_multiplier=company_resource_multiplier,
                )

            runner = EnsembleRunner(
                n_runs=self.n_ensemble,
                output_dir=os.path.join(self.output_dir, incident.name.replace(" ", "_")),
            )
            ensemble = runner.run(
                run_single,
                scenario_name=f"{incident.name}_{framework.name}".replace(" ", "_"),
            )

            framework_results[framework.name] = {
                "ensemble": ensemble,
                "framework": framework,
            }

        report = WarGameReport(
            incident=incident,
            framework_results=framework_results,
        )

        report.save(os.path.join(
            self.output_dir,
            f"wargame_{incident.name.replace(' ', '_')}_{datetime.now():%Y%m%d_%H%M%S}.json",
        ))

        return report

    def _run_incident_simulation(
        self,
        seed: int,
        incident: IncidentTemplate,
        framework: GovernanceFramework,
        temperature: float = 0.7,
        shuffle: bool = True,
        num_rounds_override: int | None = None,
        company_resource_multiplier: float = 1.0,
    ) -> dict:
        """Run one incident simulation using the unified loop."""
        from swarmcast.game_master.simulation_loop import run_simulation_loop

        engine = ResolutionEngine(seed=seed)
        world_state = GovernanceWorldState()

        for k, v in incident.initial_conditions.items():
            if k in world_state.economic_indicators:
                world_state.economic_indicators[k] = v

        from swarmcast.game_master.severity import classify_severity
        for policy in framework.policies:
            pcopy = Policy(**policy.__dict__)
            classify_severity(pcopy, model=self.model)
            world_state.active_policies[policy.id] = pcopy

        def _scale(resources: dict[str, float]) -> dict[str, float]:
            return {k: v * company_resource_multiplier for k, v in resources.items()}

        agents = {}
        agent_resources = {}
        agent_objectives = {}
        configs = [
            ("Government", build_government_agent, {"jurisdiction": "United States"}, dict(GOVERNMENT_US.resources), GOVERNMENT_US),
            ("Large AI Company", build_company_agent, {"company_size": "large"}, _scale(TECH_COMPANY_LARGE.resources), TECH_COMPANY_LARGE),
            ("Regulator", build_regulator_agent, {"agency": "AI Oversight Agency"}, dict(framework.regulator_resources), REGULATOR),
            ("Civil Society", build_civil_society_agent, {"organization": "AI Watch"}, dict(CIVIL_SOCIETY.resources), CIVIL_SOCIETY),
        ]

        if incident.category in ("adversarial", "misuse"):
            configs.append(
                ("Bad Actor", build_bad_actor_agent, {}, _scale(BAD_ACTOR.resources), BAD_ACTOR)
            )

        for name, builder, kwargs, resources, objective in configs:
            agent_resources[name] = resources
            mem = basic_associative_memory.AssociativeMemoryBank(
                sentence_embedder=self.embedder
            )
            agents[name] = builder(
                name=name, world_state=world_state, model=self.model,
                memory_bank=mem,
                resource_getter=lambda n=name: agent_resources[n],
                **kwargs,
            )
            agent_objectives[name] = objective

        premise = (
            f"INCIDENT ALERT: {incident.name}\n\n"
            f"{incident.description}\n\n"
            f"Severity: {incident.severity.upper()}\n\n"
            f"Current governance framework: {framework.name}\n"
            f"{framework.description}\n\n"
            f"All stakeholders must respond. Each round, take ONE action."
        )

        return run_simulation_loop(
            agents=agents,
            agent_resources=agent_resources,
            agent_objectives=agent_objectives,
            world_state=world_state,
            resolution_engine=engine,
            model=self.model,
            premise=premise,
            num_rounds=num_rounds_override if num_rounds_override is not None else self.num_rounds,
            seed=seed,
            verbose=False,
            temperature=temperature,
            shuffle_agents=shuffle,
        )


class WarGameReport:
    """Comparison of governance frameworks under an incident."""

    def __init__(
        self,
        incident: IncidentTemplate,
        framework_results: dict[str, dict],
    ):
        """Store the incident and the per-framework ensemble results for later reporting."""
        self.incident = incident
        self.framework_results = framework_results

    def summary(self) -> str:
        """Return a formatted string comparing indicator means across all tested frameworks, ranked by final public trust."""
        lines = [
            f"{'=' * 60}",
            f"WAR GAME REPORT: {self.incident.name}",
            f"Severity: {self.incident.severity} | Category: {self.incident.category}",
            f"{'=' * 60}",
        ]

        for fw_name, data in self.framework_results.items():
            ensemble = data["ensemble"]
            stats = ensemble.stats
            indicators = stats.get("indicator_distributions", {})

            lines.append(f"\n{'─' * 40}")
            lines.append(f"Framework: {fw_name}")
            lines.append(f"{'─' * 40}")

            for indicator, istats in indicators.items():
                lines.append(
                    f"  {indicator}: {istats.get('mean', 0):.1f} ± {istats.get('stdev', 0):.1f}"
                )

            lines.append(f"  Relocation rate: {stats.get('relocation_rate', 'N/A')}")

        lines.append(f"\n{'=' * 60}")
        lines.append("COMPARATIVE RANKING")
        lines.append(f"{'=' * 60}")

        rankings = []
        for fw_name, data in self.framework_results.items():
            trust = (
                data["ensemble"].stats
                .get("indicator_distributions", {})
                .get("public_trust", {})
                .get("mean", 0)
            )
            rankings.append((fw_name, trust))

        rankings.sort(key=lambda x: -x[1])
        for i, (name, trust) in enumerate(rankings):
            lines.append(f"  {i + 1}. {name} (final public trust: {trust:.1f})")

        lines.append(indicator_disclaimer())
        return "\n".join(lines)

    def print_summary(self) -> None:
        """Print the war game summary to stdout."""
        print(self.summary())

    def save(self, path: str) -> None:
        """Serialize incident metadata and per-framework statistics to a JSON file at path."""
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        data = {
            "incident": {
                "name": self.incident.name,
                "description": self.incident.description,
                "severity": self.incident.severity,
                "category": self.incident.category,
            },
            "frameworks": {
                name: {
                    "framework_name": d["framework"].name,
                    "statistics": d["ensemble"].stats,
                }
                for name, d in self.framework_results.items()
            },
            "timestamp": datetime.now().isoformat(),
        }
        with open(path, "w") as f:
            json.dump(data, f, indent=2, default=str)
